# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  setup-dependencies:
    steps:
      - run: apt-get -y update &&
          apt-get -y install
          curl g++-10 git

jobs:
  build_with_cmake:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - setup-dependencies
      - run: apt-get -y update &&
          apt-get -y install cmake
      - checkout
      - run: |
          ./fetch_rocksdb_src.sh
          mkdir build && cd build
          cmake ..
          cmake --build .
          ./examples/not_supported_db_example
          ./examples/stdmap_mem_db_example

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "build-ubuntu"
  build-ubuntu:
    jobs:
      - build_with_cmake
